"""Tests for core/document/pdf_generator.py — PDF generation."""

import os
import tempfile
import pytest

from core.document.pdf_generator import PDFConfig, PDFGenerator, FPDF_AVAILABLE


@pytest.mark.skipif(not FPDF_AVAILABLE, reason="fpdf2 not installed")
class TestPDFGenerator:
    """Test PDF generation with fpdf2."""

    def test_generate_simple_report(self):
        gen = PDFGenerator(PDFConfig(title="Test Report"))
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
            output_path = f.name

        try:
            sections = [
                {"heading": "Introduction", "text": "This is a test report."},
            ]
            result = gen.generate_report(sections, output_path)
            assert result == output_path
            assert os.path.exists(output_path)
            assert os.path.getsize(output_path) > 0
        finally:
            os.unlink(output_path)

    def test_generate_report_with_key_values(self):
        gen = PDFGenerator(PDFConfig(title="KV Report"))
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
            output_path = f.name

        try:
            sections = [
                {
                    "heading": "Farmer Details",
                    "key_value": [
                        ("Name", "Ramu Kumar"),
                        ("District", "Indore"),
                        ("Crop", "Wheat"),
                    ],
                },
            ]
            result = gen.generate_report(sections, output_path)
            assert result is not None
            assert os.path.exists(output_path)
        finally:
            os.unlink(output_path)

    def test_generate_report_with_table(self):
        gen = PDFGenerator(PDFConfig(title="Table Report"))
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
            output_path = f.name

        try:
            sections = [
                {
                    "heading": "Price Comparison",
                    "table": {
                        "columns": [
                            {"header": "Market", "width": 60},
                            {"header": "Price (Rs/q)", "width": 40, "align": "R"},
                            {"header": "Date", "width": 40},
                        ],
                        "rows": [
                            ["Indore Mandi", "2500", "2024-01-15"],
                            ["Bhopal Mandi", "2450", "2024-01-15"],
                            ["Delhi Mandi", "2600", "2024-01-15"],
                        ],
                    },
                },
            ]
            result = gen.generate_report(sections, output_path)
            assert result is not None
        finally:
            os.unlink(output_path)

    def test_generate_report_multiple_sections(self):
        gen = PDFGenerator(
            PDFConfig(
                title="Full Report",
                header_text="BharatAI Platform",
                footer_text="Generated by BharatAI",
            )
        )
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
            output_path = f.name

        try:
            sections = [
                {"heading": "Summary", "text": "Executive summary here."},
                {
                    "heading": "Details",
                    "key_value": [("Status", "Active"), ("Score", "85/100")],
                },
                {
                    "heading": "Data",
                    "table": {
                        "columns": [
                            {"header": "Item", "width": 60},
                            {"header": "Value", "width": 40},
                        ],
                        "rows": [["A", "100"], ["B", "200"]],
                    },
                },
            ]
            result = gen.generate_report(sections, output_path)
            assert result is not None
            # PDF should be reasonably sized
            size = os.path.getsize(output_path)
            assert size > 100
        finally:
            os.unlink(output_path)

    def test_generate_report_empty_sections(self):
        gen = PDFGenerator()
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
            output_path = f.name

        try:
            result = gen.generate_report([], output_path)
            assert result is not None  # Empty PDF is still valid
        finally:
            os.unlink(output_path)


class TestPDFConfig:
    """Test PDF configuration."""

    def test_default_config(self):
        config = PDFConfig()
        assert config.title == "BharatAI Document"
        assert config.orientation == "P"
        assert config.page_size == "A4"
        assert config.font_family == "Helvetica"

    def test_custom_config(self):
        config = PDFConfig(
            title="Custom Report",
            orientation="L",
            font_size=12,
        )
        assert config.title == "Custom Report"
        assert config.orientation == "L"
        assert config.font_size == 12


class TestPDFGeneratorDegradation:
    """Test behavior when fpdf2 is not available."""

    def test_generate_without_fpdf(self):
        if FPDF_AVAILABLE:
            pytest.skip("fpdf2 is installed — cannot test degradation")
        gen = PDFGenerator()
        result = gen.generate_report([{"text": "hello"}], "/tmp/test.pdf")
        assert result is None
